variables:
  S3_BASE: https://s3.getnoc.com
  S3_BUCKET: tower

stages:
  - lint
  - test
  - build
  - upload
  - build_image

flake8:
  stage: lint
  image: registry.getnoc.com/infrastructure/noc-lint:master
  script:
    - flake8 tower/
  tags:
    - docker
  except:
    - master
    - tags

build_tgz:
  stage: build
  image: python:2.7-alpine
  before_script:
    - export VERSION=$(cat VERSION)
    - if [ -d dist ]; then  rm -R dist/*.zip; fi
  script:
    - python setup.py sdist --format=zip
  artifacts:
    paths:
      - dist/*.zip
  tags:
    - docker

upload:
  stage: upload
  image: registry.getnoc.com/infrastructure/s3helper:master
  script:
    - export VERSION=$(cat VERSION)
    - export FNAME=noc-tower-${VERSION}.zip
    - /tmp/mc -q cp dist/$FNAME cdn/$S3_BUCKET/noc-tower-master.zip
    - if [ -n "${CI_BUILD_TAG}" ]; then /tmp/mc -q cp dist/$FNAME cdn/$S3_BUCKET/noc-tower-${VERSION}.zip; fi
    - if [ -n "${CI_BUILD_TAG}" ]; then /tmp/mc -q cp dist/$FNAME cdn/$S3_BUCKET/noc-tower-latest.zip; fi
  dependencies:
    - build_tgz
  tags:
    - docker
  only:
    - tags@noc/tower
    - master@noc/tower

check_docker_buildable_debian:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID} -f contrib/docker/Dockerfile .
  tags:
    - shell

check_docker_buildable_alpine:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t ${CI_COMMIT_REF_SLUG}-${CI_JOB_ID} -f contrib/docker/Dockerfile.alpine .
  tags:
    - shell

build_image_debian:
  stage: build
  before_script:
    - export VERSION=$(cat VERSION)
    - export CONTAINER_NAME=${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_NAME -f contrib/docker/Dockerfile .
    - docker push $CONTAINER_NAME
    - if [ -n "${CI_BUILD_TAG}" ]; then docker tag $CONTAINER_NAME ${CI_REGISTRY_IMAGE}:${CI_BUILD_TAG}; docker push $CI_REGISTRY_IMAGE:${CI_BUILD_TAG}; fi
    - if [ -n "${CI_BUILD_TAG}" ]; then docker tag $CONTAINER_NAME ${CI_REGISTRY_IMAGE}:latest; docker push ${CI_REGISTRY_IMAGE}:latest; fi
  tags:
    - shell
  only:
    - tags@noc/tower
    - master@noc/tower

build_image_alpine:
  stage: build
  before_script:
    - export VERSION=$(cat VERSION)
    - export CONTAINER_NAME=${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}_alpine
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_NAME  -f contrib/docker/Dockerfile.alpine .
    - docker push $CONTAINER_NAME
    - if [ -n "${CI_BUILD_TAG}" ]; then docker tag $CONTAINER_NAME ${CI_REGISTRY_IMAGE}:${CI_BUILD_TAG}_alpine; docker push $CI_REGISTRY_IMAGE:${CI_BUILD_TAG}_alpine; fi
    - if [ -n "${CI_BUILD_TAG}" ]; then docker tag $CONTAINER_NAME ${CI_REGISTRY_IMAGE}:alpine; docker push ${CI_REGISTRY_IMAGE}:alpine; fi
  tags:
    - shell
  only:
    - tags@noc/tower
    - master@noc/tower
