variables:
  PROXY: http://192.168.60.21:3128
  REG_NAME: registry.getnoc.com
  S3_BASE: https://s3.getnoc.com
  S3_BUCKET: tower

stages:
  - build
  - upload_artifact
  - build_image

build_tgz:
  stage: build
  image: python:2.7.11-alpine
  before_script:
    - export VERSION=$(cat VERSION)
    - if [ -d dist ]; then  rm -R dist/*.zip; fi
  script:
    - apk add --update py-pep8 py-setuptools
    - pep8 --ignore=E265,E266,E501,E402 .
    - python setup.py sdist --format=zip
  artifacts:
    paths:
      - dist/*.zip
  tags:
    - docker

upload_artifact:
  stage: upload_artifact
  script:
    - export VERSION=$(cat VERSION)
    - export FNAME=noc-tower-${VERSION}.zip
    - docker run --rm -e S3_BASE=$S3_BASE -e S3_BUCKET=$S3_BUCKET -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY -e AWS_SECRET_KEY=$AWS_SECRET_KEY -e FILE=${FNAME} -e DEST_FILE=noc-tower-master.zip -v $PWD/dist:/cd registry.getnoc.com/infrastructure/s3helper:master
    - if [ -n "${CI_BUILD_TAG}" ]; then  docker run --rm -e S3_BASE=$S3_BASE -e S3_BUCKET=$S3_BUCKET -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY -e AWS_SECRET_KEY=$AWS_SECRET_KEY -e FILE=${FNAME} -e DEST_FILE=noc-tower-${VERSION}.zip -v $PWD/dist:/cd registry.getnoc.com/infrastructure/s3helper:master ; fi
    - if [ -n "${CI_BUILD_TAG}" ]; then docker run --rm -e S3_BASE=$S3_BASE -e S3_BUCKET=$S3_BUCKET -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY -e AWS_SECRET_KEY=$AWS_SECRET_KEY -e FILE=${FNAME} -e DEST_FILE=noc-tower-latest.zip -v $PWD/dist:/cd registry.getnoc.com/infrastructure/s3helper:master ; fi
  dependencies:
    - build_tgz
  tags:
    - shell

build_image:
  stage: build_image
  before_script:
    - export VERSION=$(cat VERSION)
    - export CONTAINER_NAME=$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REG_NAME
    - docker build --build-arg="http_proxy=$PROXY" --build-arg="https_proxy=$PROXY" --build-arg=VERSION=${VERSION} -t $CONTAINER_NAME .
    - docker push registry.gitlab.com/nocproject/tower:master
    - if [ -n "${CI_BUILD_TAG}" ]; then docker tag $CONTAINER_NAME $CI_REGISTRY_IMAGE:${CI_BUILD_TAG}; docker push $CI_REGISTRY_IMAGE:${CI_BUILD_TAG}; fi
    - if [ -n "${CI_BUILD_TAG}" ]; then docker tag $CONTAINER_NAME $CI_REGISTRY_IMAGE:latest; docker push $CI_REGISTRY_IMAGE:latest; fi
  dependencies:
    - build_tgz
  tags:
    - shell
