stages:
  - build
  - upload_artifact
  - build_image

build_tgz:
  stage: build
  image: python:2.7.11-alpine
  before_script:
    - export VERSION=$(cat VERSION)
    - if [ -d dist ]; then  rm -R dist/*.zip; fi
  script:
    - apk add --update py-pep8 py-setuptools
    - pep8 --ignore=E265,E266,E501,E402 .
    - python setup.py sdist --format=zip
  artifacts:
    paths:
      - dist/*.zip
  tags:
    - dind

upload_artifact:
  stage: upload_artifact
  script:
    - export VERSION=$(cat VERSION)
    - export FNAME=noc-tower-${VERSION}.zip
    - env | sort
    - echo "put dist/${FNAME} tower/noc-tower-master.zip" | sftp -P 2228 ci@cdn.nocproject.org
    - if [ -n "${CI_BUILD_TAG}"	]; then echo "put dist/${FNAME} tower/noc-tower-${VERSION}.zip" | sftp -P 2228 ci@cdn.nocproject.org; fi
    - if [ -n "${CI_BUILD_TAG}"	]; then echo "put dist/${FNAME} tower/noc-tower-latest.zip" | sftp -P 2228 ci@cdn.nocproject.org; fi
  dependencies:
    - build_tgz
  tags:
    - shell

build_image:
  stage: build_image
  before_script:
    - export VERSION=$(cat VERSION)
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --build-arg="http_proxy=http://192.168.60.21:3128" --build-arg="https_proxy=http://192.168.60.21:3128" --build-arg=VERSION=${VERSION} -t registry.gitlab.com/nocproject/tower:master .
    - docker push registry.gitlab.com/nocproject/tower:master
    - if [ -n "${CI_BUILD_TAG}"	]; then docker tag registry.gitlab.com/nocproject/tower:master registry.gitlab.com/nocproject/tower:${CI_BUILD_TAG}; docker push registry.gitlab.com/nocproject/tower:${CI_BUILD_TAG}; fi
    - if [ -n "${CI_BUILD_TAG}"	]; then docker tag registry.gitlab.com/nocproject/tower:master registry.gitlab.com/nocproject/tower:latest; docker push registry.gitlab.com/nocproject/tower:latest; fi
  dependencies:
    - build_tgz
  tags:
    - shell