version: '2.1'
services:
  tower:
    image: registry.getnoc.com/noc/tower:master
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - "/opt/tower/var:/opt/tower/var/"
      #see for details https://groups.google.com/forum/#!topic/ansible-project/y8ohlv_dRi4
      - "$PWD/root:/root"
## provide them only for distributed installations
## for single node installation there is no need for consul info
    environment:
#      PROMETHEUS_ENABLED: "True"
#      INFLUXDB_ENABLED: "False"
      HISTCONTROL: "ignoreboth:erasedups"
#      MONGO_VERSION: 3.4
#      POSTGRES_VERSION: 9.6


