FROM alpine:3.6 as builder

RUN mkdir /mnt/tower
WORKDIR /mnt/tower/
COPY . /mnt/tower/
RUN apk add --update  py2-cffi  py-virtualenv gcc python-dev musl-dev  libffi-dev openssl-dev ca-certificates
RUN python setup.py sdist --format=zip

WORKDIR /opt/tower
RUN virtualenv /opt/tower && ./bin/pip install /mnt/tower/dist/*.zip

FROM python:2.7-alpine3.6

ENV ANSIBLE_HOST_KEY_CHECKING=False \
    ANSIBLE_SSH_PIPELINING=1 \
    ANSIBLE_STDOUT_CALLBACK=debug \
    PYTHONUNBUFFERED=1 \
    VERSION=${VERSION} \
    PS1="\$(date +%H:%M:%S) \h \w \\$ " \
    PYTHONPATH=/opt/tower/lib/python2.7/site-packages/:/usr/local/lib/python2.7:/usr/local/lib/python2.7/site-packages

COPY --from=builder /opt/tower /opt/tower

# install systemv packages
RUN  apk add --update ca-certificates openssh-client vim sqlite curl git libffi

WORKDIR /opt/tower

COPY entrypoint-alpine.sh /entrypoint.sh

STOPSIGNAL SIGINT

ENTRYPOINT ["/entrypoint.sh"]

VOLUME /opt/tower/var/

EXPOSE 8888

CMD ["./bin/tower-web"]