version: '2.1'
services:
  tower:
    image: registry.getnoc.com/noc/tower:master_alpine
    restart: always
    hostname: TEST-TOWER
    ports:
      - "8888:8888"
    volumes:
      - "/opt/tower/var:/opt/tower/var/"
      #see for details https://groups.google.com/forum/#!topic/ansible-project/y8ohlv_dRi4
      - "$PWD/root:/root"
      # use it for development purpose
      #- "$PWD/var:/opt/tower/var/"
      #- "$PWD/tower:/opt/tower/lib/python2.7/site-packages/tower/"
      #- "$PWD/config.db:/opt/tower/var/tower/db/config.db"
    environment:
      HISTCONTROL: "ignoreboth:erasedups"
      NOC_ENV: NOC
      # development only settings
      #ANSIBLE_LOAD_CALLBACK_PLUGINS: 1
      #ANSIBLE_STDOUT_CALLBACK: debug
      #ANSIBLE_CALLBACK_WHITELIST: timer,profile_tasks
      # replace NOC with your environment name
      ANSIBLE_ROLES_PATH: /opt/tower/var/tower/playbooks/NOC/additional_roles:/opt/tower/var/tower/playbooks/NOC/system_roles:/opt/tower/var/tower/playbooks/NOC/noc_roles
