FROM alpine:3.9 as builder

RUN mkdir /mnt/tower
WORKDIR /mnt/tower/
RUN apk add --no-cache --update \
    py2-cffi \
    py-virtualenv \
    gcc \
    python-dev \
    musl-dev \
    libffi-dev \
    openssl-dev \
    ca-certificates \
    make
COPY . /mnt/tower/
RUN python setup.py sdist --format=zip

WORKDIR /opt/tower
RUN virtualenv /opt/tower \
    && ./bin/pip install ansible==2.7.11 \
    && ./bin/pip install /mnt/tower/dist/*.zip

FROM python:2.7-alpine3.9

ENV ANSIBLE_HOST_KEY_CHECKING=False \
    ANSIBLE_SSH_PIPELINING=1 \
    ANSIBLE_STDOUT_CALLBACK=debug \
    PYTHONUNBUFFERED=1 \
    PS1="\$(date +%H:%M:%S) \h \w \\$ " \
    PATH=/opt/tower/bin:${PATH} \
    PYTHONPATH=/opt/tower/lib/python2.7/site-packages/:/usr/local/lib/python2.7:/usr/local/lib/python2.7/site-packages

COPY --from=builder /opt/tower /opt/tower

# install systemv packages
RUN  apk add --no-cache --update \
    ca-certificates \
    openssh-client \
    vim \
    sqlite \
    curl \
    git \
    libffi \
    openssl \
    && adduser  -S -s /bin/sh -D -H -u 1201 tower

WORKDIR /opt/tower

COPY contrib/docker/entrypoint-alpine.sh /entrypoint.sh

STOPSIGNAL SIGINT

ENTRYPOINT ["/entrypoint.sh"]

VOLUME /opt/tower/var/

EXPOSE 8888

CMD ["./bin/tower-web"]
