upstream noc-tower-web-http {
    server 127.0.0.1:8888;
}

server {
    listen 80;
    server_name tower;

    access_log  /var/log/nginx/tower.access.log;
    error_log  /var/log/nginx/tower.error.log;

    location / {
        proxy_pass http://noc-tower-web-http;
        proxy_read_timeout 600;
        gzip on;
        gzip_types text/css text/x-js;
        proxy_set_header Host $http_host;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
