name: Build Docs
env:
  PYTHONPATH: src
on:
  push:
    paths:
      - ".github/workflows/build-docs.yml"
      - "pyproject.toml"
      - "docs/**"
      - "src/**"
      - "*.md"
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  build-push:
    name: "Build & Push Docs"
    runs-on: ubuntu-24.04
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set Up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      # Install dependencies
      - name: Install Dependencies
        run: |
          uv export \
            --extra lint \
            --no-hashes \
            --format requirements-txt\
            | grep -v -- "-e ." > /tmp/requirements.txt
          uv pip install --system -r /tmp/requirements.txt

      # Build documentation
      - name: Build & Deploy Docs
        run: mkdocs gh-deploy --strict --force
